import React, { useEffect } from 'react';
import { ELEC, FIXTURES, CIRCUIT_COLORS } from '../constants';
import { getDevicesOnCircuit } from '../circuitUtils';
import { circuitVA, circuitLoadCheck, wireGaugeCheck, projectLoadSummary, wireRunLengths } from '../loadCalc';

export default function PrintView({ project, onClose }) {
  useEffect(() => {
    const timer = setTimeout(() => {
      window.print();
    }, 800);
    return () => clearTimeout(timer);
  }, []);

  const rooms = project.rooms || [];
  const allPlacements = rooms.flatMap(r => (r.placements || []).map(p => ({ ...p, roomName: r.name })));
  const allCircuits = rooms.flatMap(r => (r.circuits || []).map(c => ({ ...c, roomName: r.name, placements: r.placements || [] })));

  // Materials summary
  const materials = {};
  allPlacements.forEach(p => {
    const key = p.name;
    if (!materials[key]) {
      materials[key] = { name: p.name, qty: 0, spec: p.spec };
    }
    materials[key].qty += (p.qty || 1);
  });
  const materialList = Object.values(materials).sort((a, b) => a.name.localeCompare(b.name));

  // Load summary
  const summary = projectLoadSummary(project);
  const demand = summary.demand;

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div className="print-view">
      <button className="btn-outline no-print print-close-btn" onClick={onClose}>
        &larr; Back
      </button>

      {/* ─── Title Block ─── */}
      <div className="print-header">
        <h1>ELECTRICAL PLAN — PERMIT SUBMISSION</h1>
        <div className="print-project-info">
          <h2>{project.name}</h2>
          {project.address && <p>{project.address}</p>}
          {project.client && <p>Client: {project.client}</p>}
          <p>Date: {today}</p>
          <p>Generated by ElectraScope</p>
        </div>
      </div>

      {/* ─── Summary Stats ─── */}
      <div className="print-summary-grid">
        <div className="print-stat">
          <div className="print-stat-num">{rooms.length}</div>
          <div className="print-stat-label">Rooms</div>
        </div>
        <div className="print-stat">
          <div className="print-stat-num">{allPlacements.length}</div>
          <div className="print-stat-label">Devices</div>
        </div>
        <div className="print-stat">
          <div className="print-stat-num">{allCircuits.length}</div>
          <div className="print-stat-label">Circuits</div>
        </div>
        <div className="print-stat">
          <div className="print-stat-num">{demand.serviceSizeRec}A</div>
          <div className="print-stat-label">Service</div>
        </div>
      </div>

      {/* ─── Panel Schedule ─── */}
      <h3 className="print-section-title">Panel Schedule</h3>
      <table className="print-table print-panel-table">
        <thead>
          <tr>
            <th style={{ width: 30 }}>#</th>
            <th>Circuit Description</th>
            <th style={{ width: 45 }}>Amps</th>
            <th style={{ width: 45 }}>Wire</th>
            <th style={{ width: 55 }}>VA</th>
            <th style={{ width: 50 }}>Load</th>
            <th style={{ width: 60 }}>Protection</th>
          </tr>
        </thead>
        <tbody>
          {allCircuits.length === 0 && (
            <tr><td colSpan={7} style={{ textAlign: 'center', color: '#999', padding: 12 }}>No circuits defined</td></tr>
          )}
          {allCircuits.map((c, i) => {
            const va = circuitVA(c, c.placements);
            const check = circuitLoadCheck(c, c.placements);
            const devices = getDevicesOnCircuit(c);
            const placementMap = new Map(c.placements.map(p => [p.id, p]));
            const deviceNames = devices.map(id => {
              const p = placementMap.get(id);
              if (!p) return null;
              const def = p.elecKey ? ELEC[p.elecKey] : (p.fixtureKey ? FIXTURES[p.fixtureKey] : null);
              return def ? (def.shortName || def.name) : p.name;
            }).filter(Boolean);

            return (
              <tr key={c.id} className={check.overloaded ? 'print-row-warn' : ''}>
                <td style={{ textAlign: 'center', fontWeight: 600 }}>{c.number}</td>
                <td>
                  <strong>{c.label || `Circuit #${c.number}`}</strong>
                  <span style={{ color: '#666', fontSize: '0.85em', marginLeft: 6 }}>
                    ({c.roomName})
                  </span>
                  <div style={{ fontSize: '0.8em', color: '#555', marginTop: 2 }}>
                    {deviceNames.join(', ') || 'No devices wired'}
                  </div>
                </td>
                <td style={{ textAlign: 'center' }}>{c.amperage}A</td>
                <td style={{ textAlign: 'center' }}>#{c.wireGauge}</td>
                <td style={{ textAlign: 'center' }}>{va.toLocaleString()}</td>
                <td style={{ textAlign: 'center', fontWeight: check.overloaded ? 700 : 400, color: check.overloaded ? '#c00' : undefined }}>
                  {check.percent}%
                </td>
                <td style={{ textAlign: 'center', fontSize: '0.85em' }}>
                  {c.gfci ? 'GFCI ' : ''}{c.afci ? 'AFCI' : ''}{!c.gfci && !c.afci ? '-' : ''}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {/* ─── Load Calculation Summary ─── */}
      <h3 className="print-section-title">Load Calculation (NEC 220)</h3>
      <table className="print-table" style={{ maxWidth: 500 }}>
        <tbody>
          <tr>
            <td><strong>Total Connected Load</strong></td>
            <td style={{ textAlign: 'right' }}>{demand.connectedVA.toLocaleString()} VA</td>
          </tr>
          <tr>
            <td><strong>Demand Load (NEC 220.42)</strong></td>
            <td style={{ textAlign: 'right' }}>{demand.demandVA.toLocaleString()} VA</td>
          </tr>
          <tr>
            <td><strong>Demand Amps (at 240V)</strong></td>
            <td style={{ textAlign: 'right' }}>{demand.demandAmps} A</td>
          </tr>
          <tr style={{ fontWeight: 700 }}>
            <td>Recommended Service Size</td>
            <td style={{ textAlign: 'right' }}>{demand.serviceSizeRec} A</td>
          </tr>
        </tbody>
      </table>

      {/* Per-circuit load details */}
      {summary.circuits.some(d => d.loadCheck.overloaded || !d.wireCheck.adequate) && (
        <div style={{ marginTop: 12, padding: 8, border: '2px solid #c00', background: '#fff5f5' }}>
          <strong style={{ color: '#c00' }}>ATTENTION — Issues Found:</strong>
          <ul style={{ margin: '4px 0', paddingLeft: 20 }}>
            {summary.circuits.filter(d => d.loadCheck.overloaded).map((d, i) => (
              <li key={`o${i}`}>Circuit #{d.circuitNumber} "{d.circuitLabel}" — overloaded at {d.loadCheck.percent}% (max 80% continuous)</li>
            ))}
            {summary.circuits.filter(d => !d.wireCheck.adequate).map((d, i) => (
              <li key={`w${i}`}>{d.wireCheck.recommendation}</li>
            ))}
          </ul>
        </div>
      )}

      {/* ─── Wire Length Estimates ─── */}
      {(() => {
        const wires = wireRunLengths(project);
        if (wires.length === 0) return null;
        return (
          <>
            <h3 className="print-section-title">Wire Length Estimates</h3>
            <table className="print-table" style={{ maxWidth: 500 }}>
              <thead>
                <tr>
                  <th>Wire Gauge</th>
                  <th style={{ textAlign: 'right' }}>Estimated Length</th>
                  <th>Circuits</th>
                </tr>
              </thead>
              <tbody>
                {wires.map((w, i) => (
                  <tr key={i}>
                    <td style={{ fontWeight: 600 }}>#{w.gauge} AWG</td>
                    <td style={{ textAlign: 'right' }}>{w.lengthFt} ft</td>
                    <td style={{ fontSize: '0.85em', color: '#666' }}>{w.circuits.map(n => `#${n}`).join(', ')}</td>
                  </tr>
                ))}
                <tr style={{ fontWeight: 700 }}>
                  <td>Total Wire</td>
                  <td style={{ textAlign: 'right' }}>{wires.reduce((s, w) => s + w.lengthFt, 0)} ft</td>
                  <td></td>
                </tr>
              </tbody>
            </table>
            <div style={{ fontSize: 10, color: '#999', marginBottom: 12 }}>
              Includes 10% routing slack. Homerun stubs estimated at 6ft. Verify on site.
            </div>
          </>
        );
      })()}

      {/* ─── Materials Summary ─── */}
      <h3 className="print-section-title" style={{ pageBreakBefore: 'auto' }}>Materials Summary</h3>
      <table className="print-table">
        <thead>
          <tr>
            <th>Item</th>
            <th style={{ width: 50 }}>Qty</th>
            <th>Specification</th>
          </tr>
        </thead>
        <tbody>
          {materialList.map((m, i) => (
            <tr key={i}>
              <td>{m.name}</td>
              <td style={{ textAlign: 'center' }}>{m.qty}</td>
              <td>{m.spec || '-'}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* ─── Per-Room Detail ─── */}
      {rooms.map(r => {
        const rp = r.placements || [];
        const rc = r.circuits || [];
        if (rp.length === 0) return null;
        return (
          <div key={r.id} className="print-room">
            <h3>{r.name} <span className="print-room-meta">({r.type}, {r.width}&apos; &times; {r.height}&apos; &times; {r.ceilingHeight || 9}&apos; ceil)</span></h3>
            <table className="print-table">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Qty</th>
                  <th>Wall</th>
                  <th>Location</th>
                  <th>Height</th>
                  <th>Circuit</th>
                  <th>Spec / Notes</th>
                </tr>
              </thead>
              <tbody>
                {rp.map(p => (
                  <tr key={p.id}>
                    <td>{p.name}</td>
                    <td>{p.qty || 1}</td>
                    <td>{p.wall ? p.wall.charAt(0).toUpperCase() + p.wall.slice(1) : '-'}</td>
                    <td>{p.location || (p.wallPos ? p.wallPos.toFixed(1) + "' from left" : '-')}</td>
                    <td>{p.mountHeight ? p.mountHeight + '"' : p.height || '-'}</td>
                    <td>{p.circuit || '-'}</td>
                    <td>{[p.spec, p.notes].filter(Boolean).join('; ') || '-'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {rc.length > 0 && (
              <div style={{ marginTop: 4, fontSize: '0.85em', color: '#555' }}>
                <strong>Circuits:</strong>{' '}
                {rc.map(c => `#${c.number} ${c.label || ''} (${c.amperage}A/${c.wireGauge}AWG)`).join(', ')}
              </div>
            )}
            {r.notes && <p className="print-room-notes"><strong>Notes:</strong> {r.notes}</p>}
          </div>
        );
      })}

      {/* ─── Footer ─── */}
      <div className="print-footer">
        <p>Generated by ElectraScope &middot; {today}</p>
        <p className="print-disclaimer">
          This electrical plan is for permit submission and planning purposes.
          All electrical work must comply with local building codes, NEC 2023,
          and applicable state/municipal amendments. A licensed electrician must
          verify all specifications before installation. Load calculations per
          NEC Article 220.
        </p>
      </div>
    </div>
  );
}
