import React, { useEffect } from 'react';
import { ELEC, FIXTURES } from '../constants';

export default function PrintView({ project, onClose }) {
  useEffect(() => {
    const timer = setTimeout(() => {
      window.print();
    }, 600);
    return () => clearTimeout(timer);
  }, []);

  const rooms = project.rooms || [];
  const allPlacements = rooms.flatMap(r => (r.placements || []).map(p => ({ ...p, roomName: r.name })));

  // Materials summary
  const materials = {};
  allPlacements.forEach(p => {
    const key = p.name;
    if (!materials[key]) {
      materials[key] = { name: p.name, qty: 0, spec: p.spec };
    }
    materials[key].qty += (p.qty || 1);
  });
  const materialList = Object.values(materials).sort((a, b) => a.name.localeCompare(b.name));

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div className="print-view">
      <button className="btn-outline no-print print-close-btn" onClick={onClose}>
        &larr; Back to Scope
      </button>

      <div className="print-header">
        <h1>ElectraScope - Electrical Plan</h1>
        <div className="print-project-info">
          <h2>{project.name}</h2>
          {project.address && <p>{project.address}</p>}
          {project.client && <p>Client: {project.client}</p>}
          <p>Date: {today}</p>
        </div>
      </div>

      <h3>Materials Summary</h3>
      <table className="print-table">
        <thead>
          <tr>
            <th>Item</th>
            <th>Total Qty</th>
            <th>Specification</th>
          </tr>
        </thead>
        <tbody>
          {materialList.map((m, i) => (
            <tr key={i}>
              <td>{m.name}</td>
              <td>{m.qty}</td>
              <td>{m.spec || '-'}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {rooms.map(r => {
        const rp = r.placements || [];
        if (rp.length === 0) return null;
        return (
          <div key={r.id} className="print-room">
            <h3>{r.name} <span className="print-room-meta">({r.type}, {r.width}&apos; &times; {r.height}&apos; &times; {r.ceilingHeight || 9}&apos; ceil)</span></h3>
            <table className="print-table">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Qty</th>
                  <th>Wall</th>
                  <th>Location</th>
                  <th>Height</th>
                  <th>Circuit</th>
                  <th>Spec / Notes</th>
                </tr>
              </thead>
              <tbody>
                {rp.map(p => (
                  <tr key={p.id}>
                    <td>{p.name}</td>
                    <td>{p.qty || 1}</td>
                    <td>{p.wall ? p.wall.charAt(0).toUpperCase() + p.wall.slice(1) : '-'}</td>
                    <td>{p.location || (p.wallPos ? p.wallPos.toFixed(1) + "' from left" : '-')}</td>
                    <td>{p.mountHeight ? p.mountHeight + '"' : p.height || '-'}</td>
                    <td>{p.circuit || '-'}</td>
                    <td>{[p.spec, p.notes].filter(Boolean).join('; ') || '-'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {r.notes && <p className="print-room-notes"><strong>Notes:</strong> {r.notes}</p>}
          </div>
        );
      })}

      <div className="print-footer">
        <p>Generated by ElectraScope &middot; {today}</p>
        <p className="print-disclaimer">All electrical work must comply with local building codes and NEC requirements. A licensed electrician should verify all specifications before installation.</p>
      </div>
    </div>
  );
}
